name: flake_check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flake-checks:
    name: flake_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            download-buffer-size = 500000000

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: rishabh5321
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run flake check and capture logs
        id: flake_check
        run: |
          nix flake check

      - name: Run flake install and capture logs
        id: flake_install_avx
        run: |
          nix profile install .#thorium-avx

      - name: Remove thorium-avx profile
        run: |
          nix profile remove thorium-avx

      - name: Run flake install and capture logs
        id: flake_install_avx2
        run: |
          nix profile install .#thorium-avx2

      - name: Remove thorium-avx2 profile
        run: |
          nix profile remove thorium-avx2

      - name: Run flake install and capture logs
        id: flake_install_sse3
        run: |
          nix profile install .#thorium-sse3

      - name: Remove thorium-sse3 profile
        run: |
          nix profile remove thorium-sse3

      - name: Run flake install and capture logs
        id: flake_install_sse4
        run: |
          nix profile install .#thorium-sse4

      - name: Remove thorium-sse4 profile
        run: |
          nix profile remove thorium-sse4
